remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

title: Codebreaker
description: "An android implementation of Bulls & Cows (aka Mastermind)"
author:
  name: Marshall Levi Eldridge
  email: l2marshall@gmail.com
  copyright: false